name: publish

on:
  push:
    branches: [ main ]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push the ipaddress image
        run: |
          docker build . --tag ghcr.io/christianwasta/ipaddress-server:latest
          docker run --add-host=host.docker.internal:host-gateway ghcr.io/christianwasta/ipaddress-server:latest
          docker push ghcr.io/christianwasta/ipaddress-server:latest
          
